//! Generate the FFT twiddle-factor master table at build time.
//!
//! A single table of `W_M^i = exp(-j·2π·i/M)` for `M = 2048` (the largest
//! transform we support), computed in f64 and stored as f32 in flash. Every
//! twiddle the mixed radix-4/2 FFT needs — `W_L^k` for any complex length
//! `L | 2048`, and the real-split factors `W_N^k` for any `N | 2048` — is a
//! strided lookup into this one table, so the transform itself calls no
//! `sin`/`cos` at run time and allocates nothing.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const MASTER: usize = 2048;

fn main() {
    let mut s = String::new();
    s.push_str("// Auto-generated by build.rs — do not edit.\n");
    let _ = writeln!(s, "pub(crate) const TW_MASTER: usize = {MASTER};");

    emit(&mut s, "TW_COS", |a| a.cos());
    emit(&mut s, "TW_SIN", |a| a.sin());

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("twiddles.rs");
    fs::write(&out, s).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}

fn emit(s: &mut String, name: &str, f: impl Fn(f64) -> f64) {
    let _ = writeln!(s, "pub(crate) static {name}: [f32; {MASTER}] = [");
    for i in 0..MASTER {
        // exp(-j·2π·i/MASTER): angle is negative so TW_SIN already carries the
        // forward-transform sign; the inverse negates it at the call site.
        let angle = -2.0 * std::f64::consts::PI * (i as f64) / (MASTER as f64);
        // Round to f32 and print the *shortest* decimal that round-trips to that
        // exact f32 — identical value, minimal digits (keeps clippy's
        // excessive_precision happy on the generated file).
        let v = f(angle) as f32;
        let _ = write!(s, "{v}f32,");
        if i % 6 == 5 {
            s.push('\n');
        }
    }
    s.push_str("];\n");
}
