"""Export selected MIT KEMAR directions as f32 HRIR pairs (Rust source).

Downloads the KEMAR *compact* set (128-tap HRIRs, 44.1 kHz, big-endian int16,
interleaved left/right; azimuth measured 0-180 deg on the RIGHT hemisphere, the
left hemisphere obtained by swapping ears), resamples to the Daisy's 48 kHz,
normalizes each pair jointly (ILD-preserving), and writes a generated Rust source
consumed by the daisy-spatializer.
"""

from __future__ import annotations

import io
import subprocess
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.signal import resample_poly

KEMAR_URL = "https://sound.media.mit.edu/resources/KEMAR/compact.tar.Z"
SRC_RATE = 44100
DST_RATE = 48000
# 48000/44100 = 160/147 in lowest terms.
UP, DOWN = 160, 147


@dataclass(frozen=True)
class Direction:
    """A KEMAR direction to export.

    `name` becomes the Rust array prefix; `elev`/`azim` select the compact file
    `elev{elev}/H{elev}e{azim:03d}a.dat`; `swap` mirrors a right-hemisphere
    measurement to the left hemisphere by swapping ears.
    """

    name: str
    elev: int
    azim: int
    swap: bool
    doc: str


# Phase 1 needs one pair; the list makes adding directions (for later phases /
# a preset bank) a one-line change, then re-run the tool.
DIRECTIONS = [
    Direction(
        name="BEHIND_LEFT",
        elev=0,
        azim=135,
        swap=True,
        doc="behind and to the left (elev 0, az 135 deg mirrored to the left "
        "hemisphere): the left ear leads and is louder.",
    ),
]


def find_repo_root(start: Path) -> Path:
    for d in [start, *start.parents]:
        cargo = d / "Cargo.toml"
        if cargo.is_file() and "[workspace]" in cargo.read_text():
            return d
    raise SystemExit("could not locate the daisy-rs workspace root")


def ensure_kemar(cache: Path) -> Path:
    """Return the extracted `compact/` dir, downloading + unpacking if absent."""
    compact = cache / "compact"
    if compact.is_dir():
        return compact
    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / "compact.tar.Z"
    if not archive.is_file():
        print(f"downloading {KEMAR_URL}")
        with urllib.request.urlopen(KEMAR_URL) as r:  # noqa: S310 (trusted MIT URL)
            archive.write_bytes(r.read())
    # .Z is LZW-compressed; gzip decompresses it on both macOS and Linux. Feed
    # the decompressed tar stream to Python's tarfile (no external tar needed).
    print("decompressing compact.tar.Z")
    raw = subprocess.run(  # noqa: S603
        ["gzip", "-dc", str(archive)], capture_output=True, check=True
    ).stdout
    import tarfile

    with tarfile.open(fileobj=io.BytesIO(raw)) as tar:
        tar.extractall(cache)  # noqa: S202 (trusted archive)
    if not compact.is_dir():
        raise SystemExit(f"expected {compact} after extraction")
    return compact


def read_hrir(compact: Path, d: Direction) -> tuple[np.ndarray, np.ndarray]:
    """Read one direction, returning (left_ear, right_ear) at 44.1 kHz."""
    path = compact / f"elev{d.elev}" / f"H{d.elev}e{d.azim:03d}a.dat"
    raw = np.fromfile(path, dtype=">i2").astype(np.float64)
    if raw.size != 256:
        raise SystemExit(f"{path}: expected 256 int16, got {raw.size}")
    file_l, file_r = raw[0::2], raw[1::2]  # interleaved left,right
    # Mirror a right-hemisphere measurement to the left by swapping ears.
    return (file_r, file_l) if d.swap else (file_l, file_r)


def process(left: np.ndarray, right: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Resample 44.1->48 kHz and joint-normalize (preserving the ILD)."""
    left = resample_poly(left, UP, DOWN)
    right = resample_poly(right, UP, DOWN)
    peak = max(np.abs(left).max(), np.abs(right).max())
    scale = 0.99 / peak if peak > 0 else 1.0
    return left * scale, right * scale


def fmt_array(name: str, ir: np.ndarray, doc: str) -> str:
    vals = [f"{float(np.float32(v)):.9g}" for v in ir]
    lines = []
    for i in range(0, len(vals), 6):
        lines.append("    " + ", ".join(vals[i : i + 6]) + ",")
    body = "\n".join(lines)
    return (
        f"/// {doc}\n"
        f"#[rustfmt::skip]\n"
        f"pub static {name}: [f32; {len(ir)}] = [\n{body}\n];\n"
    )


def main() -> None:
    root = find_repo_root(Path(__file__).resolve())
    cache = root / "tools/hrir-gen/.kemar"
    out_path = root / "crates/daisy-spatializer/src/hrir_data.rs"
    compact = ensure_kemar(cache)

    chunks = [
        "// GENERATED by tools/hrir-gen — do not edit by hand.\n"
        "//\n"
        "// MIT KEMAR compact HRIR set (Gardner & Martin, MIT Media Lab, 1994),\n"
        "// https://sound.media.mit.edu/resources/KEMAR.html — publicly\n"
        "// redistributable measurement data. Resampled 44.1 kHz -> 48 kHz\n"
        "// (scipy resample_poly 160/147) and joint-normalized per pair so the\n"
        "// interaural level difference is preserved. Regenerate with\n"
        "//   uv --directory tools/hrir-gen run hrir-gen\n"
        "\n"
        "// Measurement data, not code: style lints (literal precision/grouping,\n"
        "// near-constant coincidences) do not apply to a generated coefficient\n"
        "// table, and the compact layout is deliberate (#[rustfmt::skip] below).\n"
        "#![allow(clippy::excessive_precision, clippy::unreadable_literal, "
        "clippy::approx_constant)]\n"
    ]
    for d in DIRECTIONS:
        left, right = process(*read_hrir(compact, d))
        n = len(left)
        # Report the spatial cue as a sanity check. For a single-arrival HRIR the
        # main-peak position is the direct-path arrival, so R_peak − L_peak is an
        # unambiguous ITD (positive → left ear leads); ILD is the RMS ratio in dB
        # (positive → left ear louder). Both should be positive for a left source.
        itd = int(np.argmax(np.abs(right))) - int(np.argmax(np.abs(left)))
        rms_l = float(np.sqrt((left**2).mean()))
        rms_r = float(np.sqrt((right**2).mean()))
        ild = 20.0 * np.log10(rms_l / max(rms_r, 1e-20))
        print(
            f"{d.name}: {n} taps @ {DST_RATE} Hz  "
            f"ITD {itd:+d} samp (L leads if +)  ILD {ild:+.1f} dB (L louder if +)"
        )
        chunks.append(fmt_array(f"HRIR_{d.name}_L", left, f"{d.doc} (left ear)"))
        chunks.append(fmt_array(f"HRIR_{d.name}_R", right, f"{d.doc} (right ear)"))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(chunks))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
